version: '3.7'
services:
  authz:
    container_name: 'authz'
    image: "ekofr/authz:v0.8.3-standalone"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:80"
    environment:
      database_driver: 'sqlite'
      database_name: ':memory:'
